TypeError: The "name" argument must be of type string. Received function field
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at ServerResponse.getHeader (node:_http_outgoing:719:3)
    at ServerResponse.res.get (express/lib/response.js:794:15)
    at call (.syntest/tests/tempTest.spec.js:25:4)
    at tryCatch (.syntest/tests/tempTest.spec.js:2:1)
    at Generator._invoke (.syntest/tests/tempTest.spec.js:2:1)
    at Generator.next (.syntest/tests/tempTest.spec.js:2:1)
    at asyncGeneratorStep (.syntest/tests/tempTest.spec.js:2:1)
    at _next (.syntest/tests/tempTest.spec.js:2:1)
