TypeError: Unknown encoding: y7Iy7deLHggZDVxgMfkiqnra3IJBVDK9QYlkf1PS
    at new NodeError (node:internal/errors:399:5)
    at fromString (node:buffer:500:13)
    at Function.from (node:buffer:314:12)
    at Readable._arrayValue_function_qM3C [as push] (.syntest/instrumented/crashes/atom/atom-22894/node_modules/readable-stream/lib/_stream_readable.js:12821:24)
    at _callee$ (.syntest/tests/tempTest.spec.js:7:9)
    at tryCatch (.syntest/tests/tempTest.spec.js:1:129)
    at Generator.<anonymous> (.syntest/tests/tempTest.spec.js:1:129)
    at Generator.next (.syntest/tests/tempTest.spec.js:1:129)
    at resolve (.syntest/tests/tempTest.spec.js:2:1)
    at _next (.syntest/tests/tempTest.spec.js:2:1)
    at gen (.syntest/tests/tempTest.spec.js:2:1)
    at new Promise (<anonymous>)
    at Context.<anonymous> (.syntest/tests/tempTest.spec.js:2:1)
    at processImmediate (node:internal/timers:476:21) {
