GenericHttpException: why here !
    at NotFoundException.HttpException [as constructor] (node_modules/http-exception-transformer/exceptions/HttpException.js:22:28)
    at new NotFoundException (node_modules/http-exception-transformer/exceptions/NotFoundException.gen.js:22:28)
    at /home/yash/Desktop/files/works/projects/simple-rbs/src/modules/user/routes.ts:15:9
    at step (/home/yash/Desktop/files/works/projects/simple-rbs/src/modules/user/routes.ts:33:23)
    at Object.next (/home/yash/Desktop/files/works/projects/simple-rbs/src/modules/user/routes.ts:14:53)
    at /home/yash/Desktop/files/works/projects/simple-rbs/src/modules/user/routes.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/yash/Desktop/files/works/projects/simple-rbs/src/modules/user/routes.ts:4:12)
    at /home/yash/Desktop/files/works/projects/simple-rbs/src/modules/user/routes.ts:14:51
    at Layer.handle [as handle_request] (/home/yash/Desktop/files/works/projects/simple-rbs/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/yash/Desktop/files/works/projects/simple-rbs/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/yash/Desktop/files/works/projects/simple-rbs/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/yash/Desktop/files/works/projects/simple-rbs/node_modules/express/lib/router/layer.js:95:5)
    at /home/yash/Desktop/files/works/projects/simple-rbs/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/yash/Desktop/files/works/projects/simple-rbs/node_modules/express/lib/router/index.js:335:12)
    at next (/home/yash/Desktop/files/works/projects/simple-rbs/node_modules/express/lib/router/index.js:275:10)