{
    "crash1": {
        "crashProject": "commander",
        "trace": "    at match (<anonymous>)\n    at Help._visibleArguments_function_AoOz [as wrap] (commanderjs/lib/help.js:376:75)\n    at call (.syntest/tests/tempTest.spec.js:13:9)\n    at tryCatch (.syntest/tests/tempTest.spec.js:2:1)\n    at Generator._invoke (.syntest/tests/tempTest.spec.js:2:1)\n    at Generator.next (.syntest/tests/tempTest.spec.js:2:1)\n    at asyncGeneratorStep (.syntest/tests/tempTest.spec.js:2:1)\n    at _next (.syntest/tests/tempTest.spec.js:2:1)\n    at /local/scratch/delft-versions/syntest-javascript/.syntest/tests/tempTest.spec.js:2:1\n    at new Promise (<anonymous>)\n    at Context.<anonymous> (.syntest/tests/tempTest.spec.js:2:1)\n    at processImmediate (node:internal/timers:476:21)\n",
        "errors": [
            "TypeError: String.prototype.match called on null or undefined",
            "RangeError: Invalid count value",
            "SyntaxError: Invalid regular expression: /.{1,0}([\\s​]|$)|[^\\s​]+?([\\s​]|$)/: numbers out of order in {} quantifier",
            "TypeError: flags.split is not a function",
            "TypeError: Cannot read properties of undefined (reading 'replace')",
            "TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))",
            "TypeError: boolean true is not iterable (cannot read property Symbol(Symbol.iterator))",
            "TypeError: number 9 is not iterable (cannot read property Symbol(Symbol.iterator))"
        ]
    },
    "crash2": {
        "crashProject": "commander",
        "trace": "    at humanReadableArgName (commanderjs/lib/argument.js:139:26)\n    at map (commanderjs/lib/help.js:114:126)\n    at Array.map (<anonymous>)\n    at Help._subcommandTerm_function_eLSj [as subcommandTerm] (commanderjs/lib/help.js:114:55)\n    at call (.syntest/tests/tempTest.spec.js:20:9)\n    at tryCatch (.syntest/tests/tempTest.spec.js:2:1)\n    at Generator._invoke (.syntest/tests/tempTest.spec.js:2:1)\n    at Generator.next (.syntest/tests/tempTest.spec.js:2:1)\n    at asyncGeneratorStep (.syntest/tests/tempTest.spec.js:2:1)\n    at _next (.syntest/tests/tempTest.spec.js:2:1)\n    at /local/scratch/delft-versions/syntest-javascript/.syntest/tests/tempTest.spec.js:2:1\n    at new Promise (<anonymous>)\n    at Context.<anonymous> (.syntest/tests/tempTest.spec.js:2:1)\n    at processImmediate (node:internal/timers:476:21)\n",
        "errors": [
            "TypeError: arg.name is not a function"
        ]
    },
    "crash3": {
        "crashProject": "commander",
        "trace": "    at humanReadableArgName (commanderjs/lib/argument.js:139:26)\n    at map (commanderjs/lib/help.js:114:126)\n    at Array.map (<anonymous>)\n    at Help._visibleOptions_numeric_npmp [as subcommandTerm] (commanderjs/lib/help.js:114:55)\n    at call (.syntest/tests/tempTest.spec.js:31:21)\n    at tryCatch (.syntest/tests/tempTest.spec.js:2:1)\n    at Generator._invoke (.syntest/tests/tempTest.spec.js:2:1)\n    at Generator.next (.syntest/tests/tempTest.spec.js:2:1)\n    at asyncGeneratorStep (.syntest/tests/tempTest.spec.js:2:1)\n    at _next (.syntest/tests/tempTest.spec.js:2:1)\n",
        "errors": [
            "TypeError: arg.name is not a function"
        ]
    },
    "crash4": {
        "crashProject": "commander",
        "trace": "    at forEach (commanderjs/lib/help.js:94:86)\n    at Array.forEach (<anonymous>)\n    at Help._argumentDescription_function_RtqQ [as visibleArguments] (commanderjs/lib/help.js:93:17)\n    at call (.syntest/tests/tempTest.spec.js:15:9)\n    at tryCatch (.syntest/tests/tempTest.spec.js:2:1)\n    at Generator._invoke (.syntest/tests/tempTest.spec.js:2:1)\n    at Generator.next (.syntest/tests/tempTest.spec.js:2:1)\n    at asyncGeneratorStep (.syntest/tests/tempTest.spec.js:2:1)\n    at _next (.syntest/tests/tempTest.spec.js:2:1)\n    at /local/scratch/delft-versions/syntest-javascript/.syntest/tests/tempTest.spec.js:2:1\n    at new Promise (<anonymous>)\n    at Context.<anonymous> (.syntest/tests/tempTest.spec.js:2:1)\n    at processImmediate (node:internal/timers:476:21)\n",
        "errors": [
            "TypeError: argument.name is not a function"
        ]
    },
    "crash5": {
        "crashProject": "commander",
        "trace": "    at editDistance (commanderjs/lib/suggestSimilar.js:23:474)\n    at forEach (commanderjs/lib/suggestSimilar.js:72:49)\n    at Array.forEach (<anonymous>)\n    at _optionTerm_function_abro (commanderjs/lib/suggestSimilar.js:69:14)\n    at call (.syntest/tests/tempTest.spec.js:17:9)\n    at tryCatch (.syntest/tests/tempTest.spec.js:2:1)\n    at Generator._invoke (.syntest/tests/tempTest.spec.js:2:1)\n    at Generator.next (.syntest/tests/tempTest.spec.js:2:1)\n    at asyncGeneratorStep (.syntest/tests/tempTest.spec.js:2:1)\n    at _next (.syntest/tests/tempTest.spec.js:2:1)\n    at /local/scratch/delft-versions/syntest-javascript/.syntest/tests/tempTest.spec.js:2:1\n    at new Promise (<anonymous>)\n    at Context.<anonymous> (.syntest/tests/tempTest.spec.js:2:1)\n    at processImmediate (node:internal/timers:476:21)\n",
        "errors": [
            "TypeError: Cannot set properties of undefined (setting '0')",
            "TypeError: Cannot read properties of undefined (reading '10')"
        ]
    },
    "crash6": {
        "crashProject": "commander",
        "trace": "    at forEach (commanderjs/lib/suggestSimilar.js:70:66)\n    at Array.forEach (<anonymous>)\n    at _wrap_function_BzXv (commanderjs/lib/suggestSimilar.js:69:14)\n    at call (.syntest/tests/tempTest.spec.js:10:9)\n    at tryCatch (.syntest/tests/tempTest.spec.js:2:1)\n    at Generator._invoke (.syntest/tests/tempTest.spec.js:2:1)\n    at Generator.next (.syntest/tests/tempTest.spec.js:2:1)\n    at asyncGeneratorStep (.syntest/tests/tempTest.spec.js:2:1)\n    at _next (.syntest/tests/tempTest.spec.js:2:1)\n    at /local/scratch/delft-versions/syntest-javascript/.syntest/tests/tempTest.spec.js:2:1\n    at new Promise (<anonymous>)\n    at Context.<anonymous> (.syntest/tests/tempTest.spec.js:2:1)\n    at processImmediate (node:internal/timers:476:21)\n",
        "errors": [
            "TypeError: Cannot read properties of undefined (reading 'length')"
        ]
    },
    "crash7": {
        "crashProject": "commander",
        "trace": "",
        "errors": [
            "Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure \"done()\" is called; if returning a Promise, ensure it resolves. (/local/scratch/delft-versions/syntest-javascript/.syntest/FID-1691983836282-sSgFJRZi8B5YJ1NMhtY55y/tests/tempTest.spec.js)"
        ]
    }
}
