TypeError: fn.apply is not a function
    at done (express/lib/router/index.js:641:15)
    at next (express/lib/router/index.js:210:14)
    at Function.handle (express/lib/router/index.js:174:3)
    at Object.handle (express/lib/application.js:176:10)
    at call (.syntest/tests/tempTest.spec.js:8:31)
    at tryCatch (.syntest/tests/tempTest.spec.js:2:1)
    at Generator._invoke (.syntest/tests/tempTest.spec.js:2:1)
    at Generator.next (.syntest/tests/tempTest.spec.js:2:1)
    at asyncGeneratorStep (.syntest/tests/tempTest.spec.js:2:1)
    at _next (.syntest/tests/tempTest.spec.js:2:1)
