TypeError: (0 , _v8CompileCache.getMainName) is not a function
    at _callee$ (.syntest/tests/tempTest.spec.js:4:24)
    at tryCatch (.syntest/tests/tempTest.spec.js:1:129)
    at Generator.<anonymous> (.syntest/tests/tempTest.spec.js:1:129)
    at Generator.next (.syntest/tests/tempTest.spec.js:1:129)
    at asyncGeneratorStep (.syntest/tests/tempTest.spec.js:1:129)
    at defineProperty (.syntest/tests/tempTest.spec.js:2:1)
    at /local/tmp/oliverphil/4169208.2/syntest-crash-reproduction/.syntest/tests/tempTest.spec.js:2:1
    at new Promise (<anonymous>)
    at Context.<anonymous> (.syntest/tests/tempTest.spec.js:2:1)
    at processImmediate (node:internal/timers:476:21)
